# Change these first
owner: TheRainbowDev # Your GitHub organization or username
repo: upptime-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: Main Website
    url: https://therainbow.dev
  - name: Website Hosting
    url: https://rainbowdev.host

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.therainbow.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page - The Rainbow Dev
  introTitle: "**The Rainbow Dev** is a small and quirky team of web and mobile app developers."
  introMessage: We're keen to keep our systems up and running as much as possible; however, sometimes things happen, and you can find out about any gremlins here.
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://therainbow.dev

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
